package-lock.json, package.json, src/Store.js
* * *
* * *
- Redux 버전 충돌로 인해 리펙토링 시도
* * *
- npm install @reduxjs/toolkit  설치하여 버전 통일 하였습니다.
* * *
- 기존 Store 코드를 수정 하였습니다. 
- 하기와 같이 참고 부탁드립니다.
```
import { configureStore } from '@reduxjs/toolkit';
import rootReducer from './modules'; // 루트 리듀서
const store = configureStore({
reducer: rootReducer,
middleware: (getDefaultMiddleware) => getDefaultMiddleware(), // 기본 미들웨어 사용
// Redux DevTools Extension은 자동으로 활성화됩니다.
});
export default store;
```
* * *
- 테스트시 정상동작 한걸 확인 할 수 있습니다.
* * *
=> [Bug]🐞Redux Refactoring

src/components/common/Header.js, src/styles/mains/footer.css, src/styles/mains/header.css
* * *
- 
* * *
* * *
- 메인 홈 메인 메뉴 수정 중
* * *
- 피그마와 다르게 메인 메뉴에 해당하는 서브 메뉴만 띄우기로 함
* * *
- 메인 메뉴에 handleMouseEnter와 handleMouseLeave 함수를 사용하여 마우스를 over하면 서브 메뉴가 scroll down 마우스를 focus out되면 scroll up 되게 했습니다.
```
// 전체 서브메뉴 표시 상태를 관리하기 위한 상태
const [isSubMenuVisible, setIsSubMenuVisible] = useState(false);
// 전체 메인 메뉴에 마우스를 올렸을 때 모든 서브메뉴를 표시하는 로직
const handleMouseEnter = () => setIsSubMenuVisible(true);
const handleMouseLeave = () => setIsSubMenuVisible(false);
```
* * *
- headertest
* * *
- 서브메뉴 경로 아직 설정 안 해줬습니다.
=> [Feature] 메인 홈 수정 중

src/apis/authAPI.js, src/pages/user/login.js
* * *
- 
* * *
* * *
- 회원가입과 로그인 시도 중 에러 발생 시 표시되는 메세지 수정
* * *
- [object object] -> "~ 시도 중 오류가 발생했습니다"
* * *
* * *
* * *
=> [Refactoring] 로그인, 회원가입 에러 메세지 내용 수정

src/components/auth/AuthAction.js, src/components/auth/AuthContext.js, src/pages/fairytale/Dubing.js, src/pages/fairytale/Main.js, src/pages/fairytale/Make.js, src/pages/user/Enroll.js, src/pages/user/Enroll0.js, src/pages/user/Login.js, src/styles/chatbots/Chatbot.css, src/styles/common/Common.css, src/styles/mains/Footer.css, src/styles/mains/Header.css, src/styles/mains/Main.css
* * *
* * *
- 파일 네이밍컨벤션 리팫토링 
* * *
* * *
* * *
* * *
=> [Refactoring] 네이밍 컨벤션 

package.json, src/App.js, src/components/common/Footer.js, src/components/common/Header.js, src/pages/fairytale/Main.js, src/pages/user/Enroll.js
* * *
* * *
- import  소문자 -> 대문자 변경 
* * *
* * *
* * *
* * *
=> [Refactoring] import 파일 네이밍컨벤션

package-lock.json, package.json, src/apis/AuthAPI.js, src/components/common/Header.js
* * *
* * *
* * *
- 로그인, 로그아웃 구현
- 설명을 작성하세요.
* * *
- 로그인 백단 에러를 해결하고 로그인 기능을 구현
- 로그아웃 구현
* * *
- 로그인 후 헤더에 "환영합니다" 메세지가 표시되는 것이 느려서 코드 수정 예정입니다.
* * *
* * *
=> [Feature] 로그인/로그아웃 구현

src/App.js, src/apis/AuthAPI.js, src/components/auth/AuthContext.js, src/components/auth/AuthPath.js, src/components/common/Header.js
* * *
- 
* * *
* * *
- 로그인 후 헤더 즉시 변경 수정 완료
- (App.js) 로그인 상태에 따른 접근 관리 추가
* * *
- Context를 사용해 로그인 상태를 전역으로 관리합니다.
- App.js에서 로그인 상ㅌㅐ에 따라 접근을 관리할 수 있습니다.
- 로그인 유저 토큰에 이름, 아이디, 전화번호, 보이스아이디, 가입일자를 담았습니다.
* * *
- ![image](https://github.com/Re-Spring/DoFront/assets/140992400/f8b8e184-77e7-4bc1-8481-81287eddfb84)
- ![image](https://github.com/Re-Spring/DoFront/assets/140992400/430473cd-c536-432e-8d9a-426a9de84f86)
- useAuth를 imoport 하시면 토큰 정보가 담긴 user 객체를 사용할 수 있습니다.
* * *
* * *
- ![image](https://github.com/Re-Spring/DoFront/assets/140992400/23ea5b46-26bc-4393-a8ae-23e5430d679e)
- 로그인이 필요한 기능의 경로에 RequireAuth를 붙여주세요.
=> [BugFix & Feature] 로그인 상태 전역 관리

src/pages/fairytale/BookContent.js, src/pages/fairytale/Main.js, src/styles/mains/BookContent.css, src/styles/mains/Header.css
* * *
- 
* * *
* * *
- 동화 상세페이지 구현 중
* * *
- 
* * *
- 페이지만 만들어 뒀습니다.
* * *
- 페이지 잘 나옴
* * *
-
=> [Feature] 동화 상세 페이지 구현 중

src/apis/AuthAPI.js, src/modules/AuthModule.js, src/pages/user/FindId.js, src/pages/user/FindPw.js
* * *
- 
* * *
* * *
- 아이디 찾기
- 비밀번호 찾기
* * *
* * *
* * *
* * *
=> [Feature] 아이디, 비밀번호 찾기 구현

src/apis/MakeAPI.js, src/apis/StoryAPI.js, src/apis/VoiceAPI.js, src/apis/authAPI0.js, src/pages/fairytale/Main.js
* * *
* * *
- 메인 화면 페이지 구성
* * *
* * *
* * *
* * *
=> [Feature] 메인페이지 화면구성

.idea/.gitignore, .idea/DoFront.iml, .idea/jpa-buddy.xml, .idea/misc.xml, src/App.js, src/apis/VoiceAPI.js, src/pages/voiceCloning/Voice.js
* * *
* * *
- voiceCloning 녹음 
* * *
- voiceCloning 녹음 기능 세션스토리지에 저장
* * *
```
import React, { useState, useRef, useEffect } from 'react';
import '../../styles/voice/Voice.css';
import { useDispatch } from 'react-redux';
import { callVoiceCloningAPI } from '../../apis/VoiceAPI';
function Voice() {
const [chunks, setChunks] = useState([]);
const [audioUrl, setAudioUrl] = useState('');
const [userId, setUserId] = useState('');
const mediaRecorder = useRef(null);
const [isRecording, setIsRecording] = useState(false);
const dispatch = useDispatch();
useEffect(() => {
const audioElement = document.getElementById('audioPlayback');
audioElement.src = audioUrl || '';
audioElement.style.display = audioUrl ? 'block' : 'none';
}, [audioUrl]);
const startRecording = () => {
if (isRecording) return; …
```
=> [Feature] voiceCloning 녹음 세션저장

src/components/auth/AuthContext.js, src/pages/mypage/Info.js
* * *
- 
* * *
* * *
- 내 정보 수정 기능 완료
* * *
- 
* * *
"""
const logout = () => {
localStorage.removeItem("accessToken");
setUser(null);
};
"""
정보가 수정이 되면 로그아웃이 되도록 설정함
* * *
- 기능이 아주 잘 되어용ㅎㅎ
* * *
-
=> [Feature] 내 정보 수정 기능 완료

package-lock.json, package.json, src/apis/MakeAPI.js, src/pages/fairytale/Make.js, src/pages/fairytale/WebSocketProvider.js
* * *
* * *
- 웹 소켓 연결
- 메시지를 통한 백엔드 로직 처리
* * *
- dispatch를 통해 기능을 수행 => 웹 소켓 메시지를 통해 요청
* * *
- 아직 백그라운드 알림 안됩니다
- npm install react-use-websocket 다운로드 받아주세요!
=> [Feature] 백엔드와의 웹 소켓 연결 기능 추가

src/App.js, src/components/common/Header.js, src/pages/fairytale/SearchPage.js, src/styles/mains/SearchPage.css
=> [Feature] SearchPage

src/components/common/Chatbot.js, src/pages/fairytale/BookContent.js, src/styles/mains/BookContent.css
* * *
- 
* * *
* * *
- 챗봇 기능 구현 중
* * *
- 프론트에 있는 프롬프트를 python으로 따로 뺐습니다.
* * *
- 
* * *
- 아직 구현 중
* * *
-
=> [Feature] 챗봇 기능 구현 중

src/apis/VoiceAPI.js, src/components/auth/AuthContext.js, src/components/common/Header.js, src/pages/voiceCloning/Voice.js
* * *
- 
* * *
* * *
- 보이스클론 모듈 연결 데이터 오류 수정 완료
- 이후 클론 여부 판단으로 목소리등록 페이지 바뀌게
* * *
- 보이스클론 모듈 연결은 완료됐으며 이후에 클론이 완료된 여부를 즉각 반영해 목소리 등록 페이지 변경되도록 했습니다.
* * *
- ![image](https://github.com/Re-Spring/DoFront/assets/140992400/06a73913-aa14-48ee-bdae-92da19522b6b)
- ![image](https://github.com/Re-Spring/DoFront/assets/140992400/dc646137-dbe2-4ff0-834e-54a8cbbe88f3)
* * *
- ![image](https://github.com/Re-Spring/DoFront/assets/140992400/b5c1abdc-dcff-4149-ac6e-546f1ec7d367)
* * *
=> [BugFix, Feature] 보이스클론 모듈 연결 성공, 이후 상태 업데이트

src/pages/fairytale/Main.js, src/pages/mypage/Info.js, src/pages/voiceCloning/Voice.js, src/styles/mains/Header.css, src/styles/mains/Main.css, src/styles/mypage/Info.css
* * *
- 
* * *
* * *
- 탈퇴 메시지창 수정
- 동화 리스트에 더보기 추가
- 카테고리 글씨 진하게 추가
- 메인메뉴 마우스 커서 수정
* * *
- 
* * *
- 
* * *
- 
* * *
-
=> [Feature] 회원 탈퇴 메시지창 수정 및 동화 리스트 더보기, 카테고리 수정 및 메인메뉴 수정

package-lock.json, package.json, src/apis/MakeAPI.js, src/config/Firebase.js, src/pages/fairytale/Make.js
* * *
* * *
- 웹소켓 제거
- FCM 연결
* * *
- 기존의 웹소켓 연결 방식 -> dispatch 방식으로 변경
- Firebase.js 추가
* * *
- 아직 FCM 미구현
=> [Feature] 웹 소켓 기능 제거 및 Firebase config 파일 생성

src/pages/fairytale/MyBook.js, src/styles/mybook/MyBook.css
* * *
- 
* * *
* * *
- 내 동화 페이지 구현 중
* * *
- 
* * *
- 아직 수정 중입니다.
* * *
- 
* * *
-
=> [Feature] 내 동화 페이지 구현 중

src/App.js, src/Store.js, src/pages/admin/UserInfo.js
* * *
- 
* * *
* * *
- 리스트 페이징 처리 코드 추가
* * *
- 리스트 페이징 처리 코드 추가
* * *
```
const [currentPage, setCurrentPage] = useState();
const itemsperPage = 10;
const totalItems = expVoices?.length;
const totalPages = Math.ceil(totalItems / itemsperPage);
const startIndex = (currentPage - 1) * itemsperPage;
const endIndex = Math.min(startIndex + itemsperPage, totalItems);
const handlePageChange = (newPage) => {
if (newPage >= 1 && newPage <= totalPages) {
setCurrentPage(newPage);
}
}
```
```
<ul className='pagination'>
<li className='icon' onClick={() => handlePageChange(currentPage -1)}></li>
{Array.from({ length: totalPages }, (_, index) => (
<li
key={index}
onClick={() => handlePageChange(index +1)}
>
<a className={currentPage === index +1 ? "active" : ""}>
{index +1}
</a>
</li>
))}
<li …
```
=> [Feature] 탈퇴 회원 기간 만료 후 정보 삭제 - 2

Dockerfile
* * *
* * *
- 배포를 위한 도커파일 생성
* * *
* * *
* * *
* * *
=> [Feature] dockerfile add

src/pages/fairytale/Make.js
* * *
* * *
- 동화 생성 관련 요소 조정
* * *
- 요소 관련 내용 조정
=> [Refectoring] 동화 생성 필수 요소 추가

src/pages/fairytale/BookContent.js, src/pages/fairytale/Main.js, src/pages/fairytale/MyBook.js, src/pages/mypage/Info.js, src/styles/mains/Main.css, src/styles/mybook/MyBook.css, src/styles/mypage/Info.css
* * *
- 
* * *
* * *
- 메인 동화 리스트 나누기
* * *
- 
* * *
- allstories로 모든 동화를 받았던 것을 userstories와 adminstories로 나누었습니다.
* * *
- 잘 나누어짐
-
* * *
-
=> [Feature] 메인 동화 리스트 나누기 완료

src/pages/fairytale/BookContent.js, src/pages/fairytale/Main.js, src/pages/fairytale/MyBook.js
* * *
- 
* * *
* * *
- print, console 지움
* * *
- 
* * *
- 
* * *
- 
* * *
-
=> [Refactoring] print, console 지움

src/Store.js, src/apis/MakeAPI.js, src/apis/StoryAPI.js, src/configs/Firebase.js, src/modules/StoryModule.js, src/pages/fairytale/Make.js, src/pages/fairytale/MyBook.js
* * *
* * *
- 불필요한 코드삭제
* * *
* * *
* * *
* * *
=> [Refectoring]print로그 제거

src/App.js, src/apis/AdminAPI.js, src/apis/AuthAPI.js, src/apis/VoiceAPI.js, src/components/auth/AuthContext.js, src/components/auth/SessionTimeout.js, src/pages/admin/UserInfo.js, src/pages/mypage/CustomerService.js, src/pages/mypage/CustomerServicePostDetail.js, src/pages/mypage/CustomerServicePosts.js, src/pages/mypage/Info.js, src/pages/user/Enroll.js, src/pages/user/Login.js, src/pages/voiceCloning/Voice.js
* * *
- 
* * *
* * *
- console.log 제거
* * *
- console.log 제거
* * *
* * *
* * *
=> [Refactoring] console.log 제거

src/pages/mypage/CustomerService.js, src/pages/mypage/CustomerServicePostDetail.js, src/pages/mypage/CustomerServicePosts.js, src/styles/admin/admin.css, src/styles/mypage/CustomerService.css, src/styles/mypage/CustomerServicePostDetail.css, src/styles/mypage/CustomerServicePosts.css
* * *
- 
* * *
* * *
- 문의하기 css 수정했습니다.
* * *
* * *
* * *
* * *
=> [Refactoring] 문의하기 수정
